version: "3.8"

services:
  core:
    image: jkulba/horsea:1.0
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
    network_mode: "host"

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/data
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
